package com.example.myapplication;

import android.app.AppOpsManager;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.content.pm.ResolveInfo;
import android.net.Uri;
import android.os.Bundle;
import android.provider.Settings;
import android.view.View;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;
import com.google.android.material.floatingactionbutton.FloatingActionButton;

import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {
    RecyclerView app_list;
    FloatingActionButton ok_btn;
    AppListAdapter adapter;

    @Override
    protected void onCreate(Bundle savedInstanceState){
        super.onCreate(savedInstanceState);
        setContentView(R.layout.test21);
        app_list = findViewById(R.id.app_list);
        ok_btn = findViewById(R.id.ok_btn);
        app_list.setLayoutManager(new LinearLayoutManager(this));
        requestPermissions();
        loadAppList();
        //Autogenerated Anonymous Function
        ok_btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startAppLockService();
                setContentView(R.layout.main_app_layout);
            }
        });
    }

    public void loadAppList(){
        PackageManager packageManager = getPackageManager();
        Intent intent = new Intent(Intent.ACTION_MAIN, null);
        intent.addCategory(Intent.CATEGORY_LAUNCHER);
        List<ResolveInfo> installedApps = packageManager.queryIntentActivities(intent, 0);
        List<AppInfo> apps = new ArrayList<>();
        for(ResolveInfo info : installedApps){
            AppInfo appInfo = new AppInfo();
            appInfo.setAppLogo(info.loadIcon(packageManager));
            appInfo.setPackageName(info.activityInfo.packageName);
            appInfo.setAppName((String)info.loadLabel(packageManager));
            apps.add(appInfo);
        }
        adapter = new AppListAdapter(apps);
        app_list.setAdapter(adapter);
    }

    //Request permissions.
    //TODO: Change later to not request it each time the app is opened.
    private void requestPermissions() {
        if (!isUsageStatsPermissionGranted()) {
            Intent intent = new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS);
            startActivity(intent);
        }
        if (!Settings.canDrawOverlays(this)) {
            Intent intent = new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,
                    Uri.parse("package:" + getPackageName()));
            startActivity(intent);
        }
    }

    private boolean isUsageStatsPermissionGranted() {
        AppOpsManager appOps = (AppOpsManager) getSystemService(Context.APP_OPS_SERVICE);
        int mode = appOps.checkOpNoThrow(AppOpsManager.OPSTR_GET_USAGE_STATS, android.os.Process.myUid(), getPackageName());
        return mode == AppOpsManager.MODE_ALLOWED;
    }

    private void startAppLockService() {
        stopService(new Intent(this, AppLockService.class));
        Intent intent = new Intent(this, AppLockService.class);
        ArrayList<String> lockedApps = new ArrayList<>();
        //Weird way to do it, but sure it works in my brain
        if (adapter != null) {
            List<AppInfo> appInfoList = adapter.getAppList();
            for (AppInfo appInfo : appInfoList) {
                if (appInfo.appStatus) {
                    lockedApps.add(appInfo.getPackageName());
                    System.out.println("Added app" + appInfo.getAppName());
                }
            }
        }
        intent.putStringArrayListExtra("lockedApps", lockedApps);
        startService(intent);
    }
}